---

- name: create backup dir
  file:
    path: "{{ item }}"
    owner: tine20
    group: root
    state: directory
    mode: 0750
  with_items:
    - "{{ tinedockercompose_backup_path }}"
  become: true
  when:
    - not ansible_check_mode
    - tinedockercompose_createdirs|bool

- name: cronjob for backup
  template:
    src: tine-backup.j2
    dest: /etc/cron.d/tine-backup
    owner: root
    group: root
    mode: 0644
  become: true
