inputFiles:
  - "/etc/gomplate/templates/config.inc.php.tmpl"
  - "/etc/gomplate/templates/nginx-vhost.conf.tmpl"
  - "/etc/gomplate/templates/nginx.conf.tmpl"
  - "/etc/gomplate/templates/php-fpm.conf.tmpl"
  - "/etc/gomplate/templates/php.ini.tmpl"
  - "/etc/gomplate/templates/php-fpm.conf.tmpl"
  - "/etc/gomplate/templates/php.ini.tmpl"
  - "/etc/gomplate/templates/php-fpm.conf.tmpl"
  - "/etc/gomplate/templates/php.ini.tmpl"
  - "/etc/gomplate/templates/actionQueue.ini.tmpl"
outputFiles:
  - "/etc/tine20/config.inc.php"
  - "/etc/nginx/http.d/tine20.conf"
  - "/etc/nginx/nginx.conf"
  - "/etc/php7/php-fpm.d/www.conf"
  - "/etc/php7/php.ini"
  - "/etc/php8/php-fpm.d/www.conf"
  - "/etc/php8/php.ini"
  - "/etc/php81/php-fpm.d/www.conf"
  - "/etc/php81/php.ini"
  - "/etc/php82/php-fpm.d/www.conf"
  - "/etc/php82/php.ini"
  - "/etc/php83/php-fpm.d/www.conf"
  - "/etc/php83/php.ini"
  - "/etc/tine20/actionQueue.ini"